### ISSUE TITLE
Support ubuntu18.04

### ISSUE THREAD

**Issue by Trree** [facebook/augmented-traffic-control#360]
berk version is 7.0.2

When I exec "vagrant up", I got 
```
undefined method `site' for #<Berkshelf::Berksfile (Cleanroom)>
```

**Comment by dovodsc** [comment]
@Trree did you managed to make it work on 18.04?
