### ISSUE TITLE
 get "'module' object has no attribute 'lru_cache'" issues when install django-atc-demo-ui

### ISSUE THREAD

**Issue by jeffreyzh** [facebook/augmented-traffic-control#350]
hi all
I get this exception when I install `django-atc-demo-ui`
```
pi@raspberrypi:~ $ sudo pip install django-atc-demo-ui --no-cache-dir
Collecting django-atc-demo-ui
  Downloading django_atc_demo_ui-0.1.6-py2.py3-none-any.whl (253kB)
    100% |################################| 256kB 381kB/s
Collecting django-static-jquery==1.11.1 (from django-atc-demo-ui)
  Downloading django-static-jquery-1.11.1.tar.gz (183kB)
    100% |################################| 184kB 879kB/s
Requirement already satisfied: django-atc-api in /usr/local/lib/python2.7/dist-packages (from django-atc-demo-ui)
Collecting django-bootstrap-themes==3.3.6 (from django-atc-demo-ui)
  Downloading django-bootstrap-themes-3.3.6.tar.gz (890kB)
    100% |################################| 890kB 895kB/s
Requirement already satisfied: djangorestframework in /usr/local/lib/python2.7/dist-packages (from django-atc-api->django-atc-demo-ui)
Requirement already satisfied: atc-thrift in /usr/local/lib/python2.7/dist-packages (from django-atc-api->django-atc-demo-ui)
Collecting django>=1.4 (from django-bootstrap-themes==3.3.6->django-atc-demo-ui)
  Downloading Django-2.0.tar.gz (8.0MB)
    100% |################################| 8.0MB 212kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jGGX6k/django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jGGX6k/django/
```

I noticed this line ```Downloading Django-2.0.tar.gz (8.0MB)```, is the cause of the issues？

my python version is 2.7, django version is 1.11
```
pi@raspberrypi:~ $ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.get_version()
'1.11'
>>>
```
how can i do now? pls

**Comment by jeffreyzh** [comment]
I also try to `pip uninstall Django`,then 'pip install Django==1.10', the problem still here

**Comment by jeffreyzh** [comment]
In the end ,i forced to specify the version of djanggo，it worked：
`sudo pip install django-atc-demo-ui Django==1.10 --no-cache-dir`
