### ISSUE TITLE
Runtime error:cannot import name DUrationField

### ISSUE THREAD

**Issue by sunlinsmart** [facebook/augmented-traffic-control#299]
**Meeting the requirements:**
**ATC** has a few requirements, this section is used to make sure the requirements are met. Until you can check all the boxes, **ATC** will not work on your system.
- [ ] `atcd` runs on Linux
- [ ] `atcd` has 2 physical interfaces
 - [ ] 1 that connects to the internet (WAN)
 - [ ] 1 that connects to the local network (LAN)
- [ ] the traffic from the devices that are being shaped is routed through `atcd`
- [ ] `atcd` sees the real IP of the devices (e.g there is no **NAT** on the LAN segment)

**Checking for special atcd options:**

In some cases, `atcd` default configuration may not be suitable for your system. Use:
```
atcd -h
```
do change those default to suit your setup.
For instance, if your lan interface is `wlan0`, you should start `atcd` using:
```
atcd --atcd-lan wlan0
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Any additional information that you think is important:**

**Dumping system info:**

While this may not be required in many cases, providing the following information will help us better understand your setup.

**NOTE**: before putting the output on gist, please check its content is fine to be publically available

Run https://github.com/facebook/augmented-traffic-control/blob/master/utils/dump_system_info.sh and upload the content of the logs to [https://gist.github.com/](gist)

```
curl https://raw.githubusercontent.com/facebook/augmented-traffic-control/master/utils/dump_system_info.sh | bash -s -
```

This default to using `eth0` and `eth1` for `wan` and `lan` respectively. If you are using other interfaces (let say eth0 and wlan0 respectively), use:
```
curl https://raw.githubusercontent.com/facebook/augmented-traffic-control/master/utils/dump_system_info.sh | bash -s -  eth0 wlan0
```

**Comment by sunlinsmart** [comment]
Django Version:1.7,open the URL --http://localhost:8000,show the importError at/ cannot import name DurationField.

**Comment by chantra** [comment]
this was fixed as part of #279 

what version of ATC do you use?

**Comment by yang-scofield** [comment]
Django Version:1.7   ,python versin 2.7.6    ,I  have the same problem  open  http://localhost:8000,  i  install     ATC   use:  pip install atc_thrift atcd django-atc-api django-atc-demo-ui django-atc-profile-storage

**Comment by chantra** [comment]
@sunlinsmart @yang-scofield I believe what you are hitting is #296 actually. this is fixed in master, but not pushed to pipy.

**Comment by chantra** [comment]
I have pushed version 0.1.6 to pypi. Can you try reinstalling. Note that will depend on django 1.10

**Comment by yang-scofield** [comment]
thanks @chantra  change django 1.7 to 1.10 ,it worked !  the doc is changed : django 1.7 -->django 1.10

**Comment by chantra** [comment]
Thanks for the update @yang-scofield

**Comment by chantra** [comment]
@sunlinsmart I have pushed 0.1.6 which should solve your issue. please feel free to open a new issue if after upgrading to 0.1.6 you still have an issue.
