### ISSUE TITLE
Environment Compatibility Issues

### ISSUE THREAD

**Issue by philliplu1990** [facebook/augmented-traffic-control#296]
Hi guys,
Would like your assistance.
Running
Python 2.7.6
Django 1.10
I have followed your instructions and have run into some issues:

"/dev/atc/venv/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 85, in url
    raise TypeError('view must be a callable or a list/tuple in the case of include().')

I get this error when I run: python manage.py migrate

This is after I have changed all urls.py files to use lists instead of patterns since patterns has been deprecated starting 1.8
~/dev/atc/venv/local/lib/python2.7/site-packages/atc_api/urls.py
~/dev/atc/venv/local/lib/python2.7/site-packages/atc_demo_ui/urls.py

What can I do to remedy this?

**Comment by chantra** [comment]
@philliplu1990 
Yeah, django 1.10 is not supported yet. 
First, maybe posting a diff of your change will help to better understand what your change is about.
I assume you are referencing to https://docs.djangoproject.com/en/1.10/releases/1.8/#django-conf-urls-patterns

and the fact that it got removed in https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10

You quick solution is to downgrade to django 1.9.

Better, you can clone ATC repository and run from master, see https://github.com/facebook/augmented-traffic-control#developing-on-atc
fix the issue and create a pull request.

**Comment by philliplu1990** [comment]
@chantra 
Thank you for your response.
I created a new virtualenv and installed django 1.9 as suggested. 
When running the suggested command to install pkgs
for pkg in atc_thrift atcd \
  django-atc-api django-atc-demo-ui django-atc-profile-storage
do
  pip install $pkg
done
It seems like django is automatically upgraded to 1.10.1
Regardless, I followed the steps to edit settings.py and urls.py as suggested.
When running: python manage.py migrate
I get the same error of course. 
Even if I downgraded to 1.9 before starting atcui django project, I would see the same issue. The problem seems to stem from urls.py in atc_api and atc_demo_ui referencing urls.patterns

~/dev/atc/venv/local/lib/python2.7/site-packages/atc_api/urls.py
~/dev/atc/venv/local/lib/python2.7/site-packages/atc_demo_ui/urls.py

Hence in my original post, I edited these files to use urlpatterns = [.....] format instead of urlpatterns = patterns( ' ', ....) format.

Thank you

**Comment by philliplu1990** [comment]
@chantra 
I downgraded to 1.7
Started project named atcui
Installed pkgs
Reinstalled 1.7
Edited settings.py and urls.py
python manage.py migrate
Runs successfully

ATC server is up and running now using other commands. 
When I go to the x.x.x.x/8000 webpage I get an interesting issue:
"cannot import name DurationField"
DurationField was added in Django 1.8 :/
https://docs.djangoproject.com/en/1.10/releases/1.8/

Probably getting this error because I automatically grabbed latest version of rest_framework (3.4.6) via the atc pkgs. 
DurationField was added in 3.1.3. 
http://www.django-rest-framework.org/topics/release-notes/#31x-series

Is there a way we can remedy this? 

I am surprised more people haven't run into these issues, granted I am also very inexperienced with programming. I've been fumbling around and figuring things out as I go, but there are a lot of compatibility issues when following the documentation. 

I do appreciate your help.
Thank you

**Comment by chantra** [comment]
The durationfield was fixed as part of #279 .

I don't have a good solution to give you but debugging the issue and fixing forward to support django 1.10. This is a standard django issue more than anything super specific to atc.

**Comment by chantra** [comment]
O'rite, I got something working with 1.10...

after the changes for urls.py, there is also some changes that need to happen in settings.py (may not apply to your case though).

This https://github.com/facebook/augmented-traffic-control/pull/297

**Comment by chantra** [comment]
@philliplu1990 did you get a chance to test with those patches?

**Comment by philliplu1990** [comment]
@chantra 
Yes fixed worked! Thank you very much for your assistance. My ATC server is up and running.
Thank you again
